resolver: lts-16.14

packages:
- fp-ieee/
- rounded-hw/
- ieee-decimal/

extra-deps:
- long-double-0.1.1
- float128-0.1

# Enable support for "Half" during development
flags:
  fp-ieee:
    half: true
