#!/bin/bash
output=../cbits/rounded-riscv.inl
mustache=$(which mustache mustache-2.6)
cat <<EOF > $output
/* This file was generated by etc/gen-rounded-riscv.sh. */
EOF
$mustache c-double.yaml rounded-riscv.mustache >> $output
$mustache c-float.yaml rounded-riscv.mustache >> $output
