/* This file was generated by etc/gen-rounded-riscv.sh. */

//
// double
//

static inline ALWAYS_INLINE
double rounded_add_impl_double(native_rounding_mode mode, double a, double b)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fadd.d %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fadd.d %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fadd.d %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fadd.d %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_add_double(HsInt mode, double a, double b)
{ return rounded_add_impl_double(hs_rounding_mode_to_native(mode), a, b); }
extern double rounded_hw_add_double_up(double a, double b)
{ return rounded_add_impl_double(ROUND_UPWARD, a, b); }
extern double rounded_hw_add_double_down(double a, double b)
{ return rounded_add_impl_double(ROUND_DOWNWARD, a, b); }
extern double rounded_hw_add_double_zero(double a, double b)
{ return rounded_add_impl_double(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
double rounded_sub_impl_double(native_rounding_mode mode, double a, double b)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fsub.d %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fsub.d %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fsub.d %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fsub.d %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_sub_double(HsInt mode, double a, double b)
{ return rounded_sub_impl_double(hs_rounding_mode_to_native(mode), a, b); }
extern double rounded_hw_sub_double_up(double a, double b)
{ return rounded_sub_impl_double(ROUND_UPWARD, a, b); }
extern double rounded_hw_sub_double_down(double a, double b)
{ return rounded_sub_impl_double(ROUND_DOWNWARD, a, b); }
extern double rounded_hw_sub_double_zero(double a, double b)
{ return rounded_sub_impl_double(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
double rounded_mul_impl_double(native_rounding_mode mode, double a, double b)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fmul.d %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fmul.d %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fmul.d %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fmul.d %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_mul_double(HsInt mode, double a, double b)
{ return rounded_mul_impl_double(hs_rounding_mode_to_native(mode), a, b); }
extern double rounded_hw_mul_double_up(double a, double b)
{ return rounded_mul_impl_double(ROUND_UPWARD, a, b); }
extern double rounded_hw_mul_double_down(double a, double b)
{ return rounded_mul_impl_double(ROUND_DOWNWARD, a, b); }
extern double rounded_hw_mul_double_zero(double a, double b)
{ return rounded_mul_impl_double(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
double rounded_div_impl_double(native_rounding_mode mode, double a, double b)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fdiv.d %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fdiv.d %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fdiv.d %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fdiv.d %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_div_double(HsInt mode, double a, double b)
{ return rounded_div_impl_double(hs_rounding_mode_to_native(mode), a, b); }
extern double rounded_hw_div_double_up(double a, double b)
{ return rounded_div_impl_double(ROUND_UPWARD, a, b); }
extern double rounded_hw_div_double_down(double a, double b)
{ return rounded_div_impl_double(ROUND_DOWNWARD, a, b); }
extern double rounded_hw_div_double_zero(double a, double b)
{ return rounded_div_impl_double(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
double rounded_sqrt_impl_double(native_rounding_mode mode, double a)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fsqrt.d %0, %1, rne" : "=f"(result) : "f"(a));
        break;
    case ROUND_DOWNWARD:
        __asm__("fsqrt.d %0, %1, rdn" : "=f"(result) : "f"(a));
        break;
    case ROUND_UPWARD:
        __asm__("fsqrt.d %0, %1, rup" : "=f"(result) : "f"(a));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fsqrt.d %0, %1, rtz" : "=f"(result) : "f"(a));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_sqrt_double(HsInt mode, double a)
{ return rounded_sqrt_impl_double(hs_rounding_mode_to_native(mode), a); }
extern double rounded_hw_sqrt_double_up(double a)
{ return rounded_sqrt_impl_double(ROUND_UPWARD, a); }
extern double rounded_hw_sqrt_double_down(double a)
{ return rounded_sqrt_impl_double(ROUND_DOWNWARD, a); }
extern double rounded_hw_sqrt_double_zero(double a)
{ return rounded_sqrt_impl_double(ROUND_TOWARDZERO, a); }

static inline ALWAYS_INLINE
double rounded_fma_impl_double(native_rounding_mode mode, double a, double b, double c)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fmadd.d %0, %1, %2, %3, rne" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    case ROUND_DOWNWARD:
        __asm__("fmadd.d %0, %1, %2, %3, rdn" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    case ROUND_UPWARD:
        __asm__("fmadd.d %0, %1, %2, %3, rup" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fmadd.d %0, %1, %2, %3, rtz" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_fma_double(HsInt mode, double a, double b, double c)
{ return rounded_fma_impl_double(hs_rounding_mode_to_native(mode), a, b, c); }
extern double rounded_hw_fma_double_up(double a, double b, double c)
{ return rounded_fma_impl_double(ROUND_UPWARD, a, b, c); }
extern double rounded_hw_fma_double_down(double a, double b, double c)
{ return rounded_fma_impl_double(ROUND_DOWNWARD, a, b, c); }
extern double rounded_hw_fma_double_zero(double a, double b, double c)
{ return rounded_fma_impl_double(ROUND_TOWARDZERO, a, b, c); }

extern double rounded_hw_fma_if_fast_double(HsInt mode, double a, double b, double c)
{ return rounded_fma_impl_double(hs_rounding_mode_to_native(mode), a, b, c); }
extern double rounded_hw_fma_if_fast_double_up(double a, double b, double c)
{ return rounded_fma_impl_double(ROUND_UPWARD, a, b, c); }
extern double rounded_hw_fma_if_fast_double_down(double a, double b, double c)
{ return rounded_fma_impl_double(ROUND_DOWNWARD, a, b, c); }
extern double rounded_hw_fma_if_fast_double_zero(double a, double b, double c)
{ return rounded_fma_impl_double(ROUND_TOWARDZERO, a, b, c); }

//
// Conversion
//

static inline double rounded_int64_to_double_impl(native_rounding_mode mode, int64_t x)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fcvt.d.l %0, %1, rne" : "=f"(result) : "r"(x));
        break;
    case ROUND_DOWNWARD:
        __asm__("fcvt.d.l %0, %1, rdn" : "=f"(result) : "r"(x));
        break;
    case ROUND_UPWARD:
        __asm__("fcvt.d.l %0, %1, rup" : "=f"(result) : "r"(x));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fcvt.d.l %0, %1, rtz" : "=f"(result) : "r"(x));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_int64_to_double(HsInt mode, int64_t x)
{ return rounded_int64_to_double_impl(hs_rounding_mode_to_native(mode), x); }
extern double rounded_hw_int64_to_double_up(int64_t x)
{ return rounded_int64_to_double_impl(ROUND_UPWARD, x); }
extern double rounded_hw_int64_to_double_down(int64_t x)
{ return rounded_int64_to_double_impl(ROUND_DOWNWARD, x); }
extern double rounded_hw_int64_to_double_zero(int64_t x)
{ return rounded_int64_to_double_impl(ROUND_TOWARDZERO, x); }

static inline double rounded_word64_to_double_impl(native_rounding_mode mode, uint64_t x)
{
    double result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fcvt.d.lu %0, %1, rne" : "=f"(result) : "r"(x));
        break;
    case ROUND_DOWNWARD:
        __asm__("fcvt.d.lu %0, %1, rdn" : "=f"(result) : "r"(x));
        break;
    case ROUND_UPWARD:
        __asm__("fcvt.d.lu %0, %1, rup" : "=f"(result) : "r"(x));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fcvt.d.lu %0, %1, rtz" : "=f"(result) : "r"(x));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern double rounded_hw_word64_to_double(HsInt mode, uint64_t x)
{ return rounded_word64_to_double_impl(hs_rounding_mode_to_native(mode), x); }
extern double rounded_hw_word64_to_double_up(uint64_t x)
{ return rounded_word64_to_double_impl(ROUND_UPWARD, x); }
extern double rounded_hw_word64_to_double_down(uint64_t x)
{ return rounded_word64_to_double_impl(ROUND_DOWNWARD, x); }
extern double rounded_hw_word64_to_double_zero(uint64_t x)
{ return rounded_word64_to_double_impl(ROUND_TOWARDZERO, x); }

//
// Interval arithmetic
//

static inline double fast_fmax_double(double x, double y)
{
    // IEEE 754-2019 maximumNumber
    double result;
    __asm__("fmax.d %0, %1, %2" : "=f"(result) : "f"(x), "f"(y));
    return result;
}
static inline double fast_fmax4_double(double x, double y, double z, double w)
{
    return fast_fmax_double(fast_fmax_double(x, y), fast_fmax_double(z, w));
}
static inline double fast_fmin_double(double x, double y)
{
    // IEEE 754-2019 minimumNumber
    double result;
    __asm__("fmin.d %0, %1, %2" : "=f"(result) : "f"(x), "f"(y));
    return result;
}
static inline double fast_fmin4_double(double x, double y, double z, double w)
{
    return fast_fmin_double(fast_fmin_double(x, y), fast_fmin_double(z, w));
}

extern double rounded_hw_interval_mul_double_up(double lo1, double hi1, double lo2, double hi2)
{
    double x = rounded_mul_impl_double(ROUND_UPWARD, lo1, lo2);
    double y = rounded_mul_impl_double(ROUND_UPWARD, lo1, hi2);
    double z = rounded_mul_impl_double(ROUND_UPWARD, hi1, lo2);
    double w = rounded_mul_impl_double(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 * inf -> 0 */
    return fast_fmax4_double(x, y, z, w);
}

extern double rounded_hw_interval_mul_double_down(double lo1, double hi1, double lo2, double hi2)
{
    double x = rounded_mul_impl_double(ROUND_DOWNWARD, lo1, lo2);
    double y = rounded_mul_impl_double(ROUND_DOWNWARD, lo1, hi2);
    double z = rounded_mul_impl_double(ROUND_DOWNWARD, hi1, lo2);
    double w = rounded_mul_impl_double(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 * inf -> 0 */
    return fast_fmin4_double(x, y, z, w);
}

extern double rounded_hw_interval_mul_add_double_up(double lo1, double hi1, double lo2, double hi2, double hi3)
{
    double x = rounded_mul_impl_double(ROUND_UPWARD, lo1, lo2);
    double y = rounded_mul_impl_double(ROUND_UPWARD, lo1, hi2);
    double z = rounded_mul_impl_double(ROUND_UPWARD, hi1, lo2);
    double w = rounded_mul_impl_double(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 * inf -> 0 */
    double p = fast_fmax4_double(x, y, z, w);
    return rounded_add_impl_double(ROUND_UPWARD, p, hi3);
}

extern double rounded_hw_interval_mul_add_double_down(double lo1, double hi1, double lo2, double hi2, double lo3)
{
    double x = rounded_mul_impl_double(ROUND_DOWNWARD, lo1, lo2);
    double y = rounded_mul_impl_double(ROUND_DOWNWARD, lo1, hi2);
    double z = rounded_mul_impl_double(ROUND_DOWNWARD, hi1, lo2);
    double w = rounded_mul_impl_double(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 * inf -> 0 */
    double p = fast_fmin4_double(x, y, z, w);
    return rounded_add_impl_double(ROUND_DOWNWARD, p, lo3);
}

extern double rounded_hw_interval_div_double_up(double lo1, double hi1, double lo2, double hi2)
{
    double x = rounded_div_impl_double(ROUND_UPWARD, lo1, lo2);
    double y = rounded_div_impl_double(ROUND_UPWARD, lo1, hi2);
    double z = rounded_div_impl_double(ROUND_UPWARD, hi1, lo2);
    double w = rounded_div_impl_double(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    return fast_fmax4_double(x, y, z, w);
}

extern double rounded_hw_interval_div_double_down(double lo1, double hi1, double lo2, double hi2)
{
    double x = rounded_div_impl_double(ROUND_DOWNWARD, lo1, lo2);
    double y = rounded_div_impl_double(ROUND_DOWNWARD, lo1, hi2);
    double z = rounded_div_impl_double(ROUND_DOWNWARD, hi1, lo2);
    double w = rounded_div_impl_double(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    return fast_fmin4_double(x, y, z, w);
}

extern double rounded_hw_interval_div_add_double_up(double lo1, double hi1, double lo2, double hi2, double hi3)
{
    double x = rounded_div_impl_double(ROUND_UPWARD, lo1, lo2);
    double y = rounded_div_impl_double(ROUND_UPWARD, lo1, hi2);
    double z = rounded_div_impl_double(ROUND_UPWARD, hi1, lo2);
    double w = rounded_div_impl_double(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    double p = fast_fmax4_double(x, y, z, w);
    return rounded_add_impl_double(ROUND_UPWARD, p, hi3);
}

extern double rounded_hw_interval_div_add_double_down(double lo1, double hi1, double lo2, double hi2, double lo3)
{
    double x = rounded_div_impl_double(ROUND_DOWNWARD, lo1, lo2);
    double y = rounded_div_impl_double(ROUND_DOWNWARD, lo1, hi2);
    double z = rounded_div_impl_double(ROUND_DOWNWARD, hi1, lo2);
    double w = rounded_div_impl_double(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0; /* 0 / 0, +-inf / +-inf -> 0 */
    double p = fast_fmin4_double(x, y, z, w);
    return rounded_add_impl_double(ROUND_DOWNWARD, p, lo3);
}

//
// Vector Operations
//

extern double rounded_hw_vector_sum_double(HsInt mode, HsInt length, HsInt offset, const double *a)
{
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        {
            double s = 0.0;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_double(ROUND_TONEAREST, s, a[offset + i]);
            }
            return s;
        }
    case ROUND_DOWNWARD:
        {
            double s = 0.0;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_double(ROUND_DOWNWARD, s, a[offset + i]);
            }
            return s;
        }
    case ROUND_UPWARD:
        {
            double s = 0.0;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_double(ROUND_UPWARD, s, a[offset + i]);
            }
            return s;
        }
    case ROUND_TOWARDZERO:
        {
            double s = 0.0;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_double(ROUND_TOWARDZERO, s, a[offset + i]);
            }
            return s;
        }
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_add_double(HsInt mode, HsInt length, HsInt offsetR, double * restrict result, HsInt offsetA, const double * restrict a, HsInt offsetB, const double * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_double(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_double(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_double(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_double(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_sub_double(HsInt mode, HsInt length, HsInt offsetR, double * restrict result, HsInt offsetA, const double * restrict a, HsInt offsetB, const double * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_double(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_double(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_double(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_double(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_mul_double(HsInt mode, HsInt length, HsInt offsetR, double * restrict result, HsInt offsetA, const double * restrict a, HsInt offsetB, const double * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_double(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_double(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_double(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_double(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_fma_double(HsInt mode, HsInt length, HsInt offsetR, double * restrict result, HsInt offsetA, const double * restrict a, HsInt offsetB, const double * restrict b, HsInt offsetC, const double * restrict c)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_double(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_double(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_double(ROUND_UPWARD, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_double(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_div_double(HsInt mode, HsInt length, HsInt offsetR, double * restrict result, HsInt offsetA, const double * restrict a, HsInt offsetB, const double * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_double(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_double(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_double(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_double(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_sqrt_double(HsInt mode, HsInt length, HsInt offsetR, double * restrict result, HsInt offsetA, const double * restrict a)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_double(ROUND_TONEAREST, a[offsetA + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_double(ROUND_DOWNWARD, a[offsetA + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_double(ROUND_UPWARD, a[offsetA + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_double(ROUND_TOWARDZERO, a[offsetA + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

//
// float
//

static inline ALWAYS_INLINE
float rounded_add_impl_float(native_rounding_mode mode, float a, float b)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fadd.s %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fadd.s %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fadd.s %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fadd.s %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_add_float(HsInt mode, float a, float b)
{ return rounded_add_impl_float(hs_rounding_mode_to_native(mode), a, b); }
extern float rounded_hw_add_float_up(float a, float b)
{ return rounded_add_impl_float(ROUND_UPWARD, a, b); }
extern float rounded_hw_add_float_down(float a, float b)
{ return rounded_add_impl_float(ROUND_DOWNWARD, a, b); }
extern float rounded_hw_add_float_zero(float a, float b)
{ return rounded_add_impl_float(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
float rounded_sub_impl_float(native_rounding_mode mode, float a, float b)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fsub.s %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fsub.s %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fsub.s %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fsub.s %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_sub_float(HsInt mode, float a, float b)
{ return rounded_sub_impl_float(hs_rounding_mode_to_native(mode), a, b); }
extern float rounded_hw_sub_float_up(float a, float b)
{ return rounded_sub_impl_float(ROUND_UPWARD, a, b); }
extern float rounded_hw_sub_float_down(float a, float b)
{ return rounded_sub_impl_float(ROUND_DOWNWARD, a, b); }
extern float rounded_hw_sub_float_zero(float a, float b)
{ return rounded_sub_impl_float(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
float rounded_mul_impl_float(native_rounding_mode mode, float a, float b)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fmul.s %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fmul.s %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fmul.s %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fmul.s %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_mul_float(HsInt mode, float a, float b)
{ return rounded_mul_impl_float(hs_rounding_mode_to_native(mode), a, b); }
extern float rounded_hw_mul_float_up(float a, float b)
{ return rounded_mul_impl_float(ROUND_UPWARD, a, b); }
extern float rounded_hw_mul_float_down(float a, float b)
{ return rounded_mul_impl_float(ROUND_DOWNWARD, a, b); }
extern float rounded_hw_mul_float_zero(float a, float b)
{ return rounded_mul_impl_float(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
float rounded_div_impl_float(native_rounding_mode mode, float a, float b)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fdiv.s %0, %1, %2, rne" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_DOWNWARD:
        __asm__("fdiv.s %0, %1, %2, rdn" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_UPWARD:
        __asm__("fdiv.s %0, %1, %2, rup" : "=f"(result) : "f"(a), "f"(b));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fdiv.s %0, %1, %2, rtz" : "=f"(result) : "f"(a), "f"(b));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_div_float(HsInt mode, float a, float b)
{ return rounded_div_impl_float(hs_rounding_mode_to_native(mode), a, b); }
extern float rounded_hw_div_float_up(float a, float b)
{ return rounded_div_impl_float(ROUND_UPWARD, a, b); }
extern float rounded_hw_div_float_down(float a, float b)
{ return rounded_div_impl_float(ROUND_DOWNWARD, a, b); }
extern float rounded_hw_div_float_zero(float a, float b)
{ return rounded_div_impl_float(ROUND_TOWARDZERO, a, b); }

static inline ALWAYS_INLINE
float rounded_sqrt_impl_float(native_rounding_mode mode, float a)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fsqrt.s %0, %1, rne" : "=f"(result) : "f"(a));
        break;
    case ROUND_DOWNWARD:
        __asm__("fsqrt.s %0, %1, rdn" : "=f"(result) : "f"(a));
        break;
    case ROUND_UPWARD:
        __asm__("fsqrt.s %0, %1, rup" : "=f"(result) : "f"(a));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fsqrt.s %0, %1, rtz" : "=f"(result) : "f"(a));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_sqrt_float(HsInt mode, float a)
{ return rounded_sqrt_impl_float(hs_rounding_mode_to_native(mode), a); }
extern float rounded_hw_sqrt_float_up(float a)
{ return rounded_sqrt_impl_float(ROUND_UPWARD, a); }
extern float rounded_hw_sqrt_float_down(float a)
{ return rounded_sqrt_impl_float(ROUND_DOWNWARD, a); }
extern float rounded_hw_sqrt_float_zero(float a)
{ return rounded_sqrt_impl_float(ROUND_TOWARDZERO, a); }

static inline ALWAYS_INLINE
float rounded_fma_impl_float(native_rounding_mode mode, float a, float b, float c)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fmadd.s %0, %1, %2, %3, rne" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    case ROUND_DOWNWARD:
        __asm__("fmadd.s %0, %1, %2, %3, rdn" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    case ROUND_UPWARD:
        __asm__("fmadd.s %0, %1, %2, %3, rup" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fmadd.s %0, %1, %2, %3, rtz" : "=f"(result) : "f"(a), "f"(b), "f"(c));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_fma_float(HsInt mode, float a, float b, float c)
{ return rounded_fma_impl_float(hs_rounding_mode_to_native(mode), a, b, c); }
extern float rounded_hw_fma_float_up(float a, float b, float c)
{ return rounded_fma_impl_float(ROUND_UPWARD, a, b, c); }
extern float rounded_hw_fma_float_down(float a, float b, float c)
{ return rounded_fma_impl_float(ROUND_DOWNWARD, a, b, c); }
extern float rounded_hw_fma_float_zero(float a, float b, float c)
{ return rounded_fma_impl_float(ROUND_TOWARDZERO, a, b, c); }

extern float rounded_hw_fma_if_fast_float(HsInt mode, float a, float b, float c)
{ return rounded_fma_impl_float(hs_rounding_mode_to_native(mode), a, b, c); }
extern float rounded_hw_fma_if_fast_float_up(float a, float b, float c)
{ return rounded_fma_impl_float(ROUND_UPWARD, a, b, c); }
extern float rounded_hw_fma_if_fast_float_down(float a, float b, float c)
{ return rounded_fma_impl_float(ROUND_DOWNWARD, a, b, c); }
extern float rounded_hw_fma_if_fast_float_zero(float a, float b, float c)
{ return rounded_fma_impl_float(ROUND_TOWARDZERO, a, b, c); }

//
// Conversion
//

static inline float rounded_int64_to_float_impl(native_rounding_mode mode, int64_t x)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fcvt.s.l %0, %1, rne" : "=f"(result) : "r"(x));
        break;
    case ROUND_DOWNWARD:
        __asm__("fcvt.s.l %0, %1, rdn" : "=f"(result) : "r"(x));
        break;
    case ROUND_UPWARD:
        __asm__("fcvt.s.l %0, %1, rup" : "=f"(result) : "r"(x));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fcvt.s.l %0, %1, rtz" : "=f"(result) : "r"(x));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_int64_to_float(HsInt mode, int64_t x)
{ return rounded_int64_to_float_impl(hs_rounding_mode_to_native(mode), x); }
extern float rounded_hw_int64_to_float_up(int64_t x)
{ return rounded_int64_to_float_impl(ROUND_UPWARD, x); }
extern float rounded_hw_int64_to_float_down(int64_t x)
{ return rounded_int64_to_float_impl(ROUND_DOWNWARD, x); }
extern float rounded_hw_int64_to_float_zero(int64_t x)
{ return rounded_int64_to_float_impl(ROUND_TOWARDZERO, x); }

static inline float rounded_word64_to_float_impl(native_rounding_mode mode, uint64_t x)
{
    float result;
    switch (mode) {
    case ROUND_TONEAREST:
        __asm__("fcvt.s.lu %0, %1, rne" : "=f"(result) : "r"(x));
        break;
    case ROUND_DOWNWARD:
        __asm__("fcvt.s.lu %0, %1, rdn" : "=f"(result) : "r"(x));
        break;
    case ROUND_UPWARD:
        __asm__("fcvt.s.lu %0, %1, rup" : "=f"(result) : "r"(x));
        break;
    case ROUND_TOWARDZERO:
        __asm__("fcvt.s.lu %0, %1, rtz" : "=f"(result) : "r"(x));
        break;
    default:
        UNREACHABLE();
        abort();
    }
    return result;
}
extern float rounded_hw_word64_to_float(HsInt mode, uint64_t x)
{ return rounded_word64_to_float_impl(hs_rounding_mode_to_native(mode), x); }
extern float rounded_hw_word64_to_float_up(uint64_t x)
{ return rounded_word64_to_float_impl(ROUND_UPWARD, x); }
extern float rounded_hw_word64_to_float_down(uint64_t x)
{ return rounded_word64_to_float_impl(ROUND_DOWNWARD, x); }
extern float rounded_hw_word64_to_float_zero(uint64_t x)
{ return rounded_word64_to_float_impl(ROUND_TOWARDZERO, x); }

//
// Interval arithmetic
//

static inline float fast_fmax_float(float x, float y)
{
    // IEEE 754-2019 maximumNumber
    float result;
    __asm__("fmax.s %0, %1, %2" : "=f"(result) : "f"(x), "f"(y));
    return result;
}
static inline float fast_fmax4_float(float x, float y, float z, float w)
{
    return fast_fmax_float(fast_fmax_float(x, y), fast_fmax_float(z, w));
}
static inline float fast_fmin_float(float x, float y)
{
    // IEEE 754-2019 minimumNumber
    float result;
    __asm__("fmin.s %0, %1, %2" : "=f"(result) : "f"(x), "f"(y));
    return result;
}
static inline float fast_fmin4_float(float x, float y, float z, float w)
{
    return fast_fmin_float(fast_fmin_float(x, y), fast_fmin_float(z, w));
}

extern float rounded_hw_interval_mul_float_up(float lo1, float hi1, float lo2, float hi2)
{
    float x = rounded_mul_impl_float(ROUND_UPWARD, lo1, lo2);
    float y = rounded_mul_impl_float(ROUND_UPWARD, lo1, hi2);
    float z = rounded_mul_impl_float(ROUND_UPWARD, hi1, lo2);
    float w = rounded_mul_impl_float(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 * inf -> 0 */
    return fast_fmax4_float(x, y, z, w);
}

extern float rounded_hw_interval_mul_float_down(float lo1, float hi1, float lo2, float hi2)
{
    float x = rounded_mul_impl_float(ROUND_DOWNWARD, lo1, lo2);
    float y = rounded_mul_impl_float(ROUND_DOWNWARD, lo1, hi2);
    float z = rounded_mul_impl_float(ROUND_DOWNWARD, hi1, lo2);
    float w = rounded_mul_impl_float(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 * inf -> 0 */
    return fast_fmin4_float(x, y, z, w);
}

extern float rounded_hw_interval_mul_add_float_up(float lo1, float hi1, float lo2, float hi2, float hi3)
{
    float x = rounded_mul_impl_float(ROUND_UPWARD, lo1, lo2);
    float y = rounded_mul_impl_float(ROUND_UPWARD, lo1, hi2);
    float z = rounded_mul_impl_float(ROUND_UPWARD, hi1, lo2);
    float w = rounded_mul_impl_float(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 * inf -> 0 */
    float p = fast_fmax4_float(x, y, z, w);
    return rounded_add_impl_float(ROUND_UPWARD, p, hi3);
}

extern float rounded_hw_interval_mul_add_float_down(float lo1, float hi1, float lo2, float hi2, float lo3)
{
    float x = rounded_mul_impl_float(ROUND_DOWNWARD, lo1, lo2);
    float y = rounded_mul_impl_float(ROUND_DOWNWARD, lo1, hi2);
    float z = rounded_mul_impl_float(ROUND_DOWNWARD, hi1, lo2);
    float w = rounded_mul_impl_float(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 * inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 * inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 * inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 * inf -> 0 */
    float p = fast_fmin4_float(x, y, z, w);
    return rounded_add_impl_float(ROUND_DOWNWARD, p, lo3);
}

extern float rounded_hw_interval_div_float_up(float lo1, float hi1, float lo2, float hi2)
{
    float x = rounded_div_impl_float(ROUND_UPWARD, lo1, lo2);
    float y = rounded_div_impl_float(ROUND_UPWARD, lo1, hi2);
    float z = rounded_div_impl_float(ROUND_UPWARD, hi1, lo2);
    float w = rounded_div_impl_float(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    return fast_fmax4_float(x, y, z, w);
}

extern float rounded_hw_interval_div_float_down(float lo1, float hi1, float lo2, float hi2)
{
    float x = rounded_div_impl_float(ROUND_DOWNWARD, lo1, lo2);
    float y = rounded_div_impl_float(ROUND_DOWNWARD, lo1, hi2);
    float z = rounded_div_impl_float(ROUND_DOWNWARD, hi1, lo2);
    float w = rounded_div_impl_float(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    return fast_fmin4_float(x, y, z, w);
}

extern float rounded_hw_interval_div_add_float_up(float lo1, float hi1, float lo2, float hi2, float hi3)
{
    float x = rounded_div_impl_float(ROUND_UPWARD, lo1, lo2);
    float y = rounded_div_impl_float(ROUND_UPWARD, lo1, hi2);
    float z = rounded_div_impl_float(ROUND_UPWARD, hi1, lo2);
    float w = rounded_div_impl_float(ROUND_UPWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    float p = fast_fmax4_float(x, y, z, w);
    return rounded_add_impl_float(ROUND_UPWARD, p, hi3);
}

extern float rounded_hw_interval_div_add_float_down(float lo1, float hi1, float lo2, float hi2, float lo3)
{
    float x = rounded_div_impl_float(ROUND_DOWNWARD, lo1, lo2);
    float y = rounded_div_impl_float(ROUND_DOWNWARD, lo1, hi2);
    float z = rounded_div_impl_float(ROUND_DOWNWARD, hi1, lo2);
    float w = rounded_div_impl_float(ROUND_DOWNWARD, hi1, hi2);
    if (isnan(x)) x = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(y)) y = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(z)) z = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    if (isnan(w)) w = 0.0f; /* 0 / 0, +-inf / +-inf -> 0 */
    float p = fast_fmin4_float(x, y, z, w);
    return rounded_add_impl_float(ROUND_DOWNWARD, p, lo3);
}

//
// Vector Operations
//

extern float rounded_hw_vector_sum_float(HsInt mode, HsInt length, HsInt offset, const float *a)
{
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        {
            float s = 0.0f;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_float(ROUND_TONEAREST, s, a[offset + i]);
            }
            return s;
        }
    case ROUND_DOWNWARD:
        {
            float s = 0.0f;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_float(ROUND_DOWNWARD, s, a[offset + i]);
            }
            return s;
        }
    case ROUND_UPWARD:
        {
            float s = 0.0f;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_float(ROUND_UPWARD, s, a[offset + i]);
            }
            return s;
        }
    case ROUND_TOWARDZERO:
        {
            float s = 0.0f;
            for (HsInt i = 0; i < length; ++i) {
                s = rounded_add_impl_float(ROUND_TOWARDZERO, s, a[offset + i]);
            }
            return s;
        }
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_add_float(HsInt mode, HsInt length, HsInt offsetR, float * restrict result, HsInt offsetA, const float * restrict a, HsInt offsetB, const float * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_float(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_float(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_float(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_add_impl_float(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_sub_float(HsInt mode, HsInt length, HsInt offsetR, float * restrict result, HsInt offsetA, const float * restrict a, HsInt offsetB, const float * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_float(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_float(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_float(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sub_impl_float(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_mul_float(HsInt mode, HsInt length, HsInt offsetR, float * restrict result, HsInt offsetA, const float * restrict a, HsInt offsetB, const float * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_float(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_float(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_float(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_mul_impl_float(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_fma_float(HsInt mode, HsInt length, HsInt offsetR, float * restrict result, HsInt offsetA, const float * restrict a, HsInt offsetB, const float * restrict b, HsInt offsetC, const float * restrict c)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_float(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_float(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_float(ROUND_UPWARD, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_fma_impl_float(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i], c[offsetC + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_div_float(HsInt mode, HsInt length, HsInt offsetR, float * restrict result, HsInt offsetA, const float * restrict a, HsInt offsetB, const float * restrict b)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_float(ROUND_TONEAREST, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_float(ROUND_DOWNWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_float(ROUND_UPWARD, a[offsetA + i], b[offsetB + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_div_impl_float(ROUND_TOWARDZERO, a[offsetA + i], b[offsetB + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}

extern void rounded_hw_vector_sqrt_float(HsInt mode, HsInt length, HsInt offsetR, float * restrict result, HsInt offsetA, const float * restrict a)
{
    // TODO: Use SIMD
    switch (hs_rounding_mode_to_native(mode)) {
    case ROUND_TONEAREST:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_float(ROUND_TONEAREST, a[offsetA + i]);
        }
        break;
    case ROUND_DOWNWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_float(ROUND_DOWNWARD, a[offsetA + i]);
        }
        break;
    case ROUND_UPWARD:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_float(ROUND_UPWARD, a[offsetA + i]);
        }
        break;
    case ROUND_TOWARDZERO:
        for (HsInt i = 0; i < length; ++i) {
            result[offsetR + i] = rounded_sqrt_impl_float(ROUND_TOWARDZERO, a[offsetA + i]);
        }
        break;
    default:
        UNREACHABLE();
        abort();
    }
}
