on:
  push:
    paths:
      - '**'
      - '!rounded-hw/**'
  pull_request:
    paths:
      - '**'
      - '!rounded-hw/**'
name: Build fp-ieee
jobs:
  fp-ieee:
    name: fp-ieee
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.7', '9.0.2', '9.2.8', '9.4.8', '9.6.7', '9.8.4', '9.10', '9.12', '9.14']
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-14, windows-latest]
        flags: ['', '--flags "fma3 f16c half"', '--flags half', '--flags float128', '--flags pure-hs']
        exclude:
          # float128-0.1 may not support recent GHC (should we try --allow-newer?)
          # - ghc: '<some future version>'
          #   flags: '--flags float128'
          - os: macos-15-intel
            flags: '--flags float128'
          - os: macos-14
            flags: '--flags float128'
          - os: windows-latest
            flags: '--flags float128'
          # Fragile
          - os: macos-15-intel
            flags: '--flags "fma3 f16c half"'
          - os: macos-14
            flags: '--flags "fma3 f16c half"' # Makes no sense on Arm64
          - os: ubuntu-24.04-arm
            flags: '--flags "fma3 f16c half"' # Makes no sense on Arm64
          # macos-14/ubuntu-24.04-arm (Arm64) doesn't support older GHC
          # 8.10.7 and 9.0.2 are excluded because haskell-actions/setup doesn't install LLVM
          - os: macos-14
            ghc: '8.6.5'
          - os: macos-14
            ghc: '8.8.4'
          - os: macos-14
            ghc: '8.10.7'
          - os: macos-14
            ghc: '9.0.2'
          - os: ubuntu-24.04-arm
            ghc: '8.6.5'
          - os: ubuntu-24.04-arm
            ghc: '8.8.4'
          - os: ubuntu-24.04-arm
            ghc: '8.10.7'
          - os: ubuntu-24.04-arm
            ghc: '9.0.2'
    steps:
      - uses: actions/checkout@v6

      - uses: haskell-actions/setup@v2
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - name: Configure (with UBSan)
        run: |
          cabal configure fp-ieee --ghc-options="-fno-ignore-asserts -optc-fsanitize=undefined -optl-fsanitize=undefined" --enable-tests --enable-benchmarks ${{ matrix.flags }}
          echo "UBSAN_OPTIONS=halt_on_error=1" >> "$GITHUB_ENV"
        if: ${{ runner.os != 'Windows' }}

      - name: Configure (without UBSan)
        run: cabal configure fp-ieee --ghc-options=-fno-ignore-asserts --enable-tests --enable-benchmarks ${{ matrix.flags }}
        if: ${{ runner.os == 'Windows' }}

      - name: Build
        run: cabal build fp-ieee

      - name: Test
        run: cabal test fp-ieee
        if: ${{ runner.os != 'macOS' && runner.os != 'Windows' }}

      # doctest on macOS/Windows is broken
      - name: Test (without doctest)
        run: cabal test fp-ieee:fp-ieee-test
        if: ${{ runner.os == 'macOS' || runner.os == 'Windows' }}
