on:
  push:
    paths:
      - '**'
      - '!fp-ieee/**'
  pull_request:
    paths:
      - '**'
      - '!fp-ieee/**'
name: Build rounded-hw
jobs:
  rounded-hw:
    name: rounded-hw
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.7', '9.0.2', '9.2.8', '9.4.8', '9.6.7', '9.8.4', '9.10', '9.12', '9.14']
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-14, windows-latest]
        flags: ['', '--flags x87-long-double', '--flags pure-hs']
        exclude:
          # - ghc: '<some future version>'
          #   flags: '--flags x87-long-double'
          # macos-14/ubuntu-24.04-arm (Arm64) doesn't support older GHC
          # 8.10.7 and 9.0.2 are excluded because haskell-actions/setup doesn't install LLVM
          - os: macos-14
            ghc: '8.6.5'
          - os: macos-14
            ghc: '8.8.4'
          - os: macos-14
            ghc: '8.10.7'
          - os: macos-14
            ghc: '9.0.2'
          - os: ubuntu-24.04-arm
            ghc: '8.6.5'
          - os: ubuntu-24.04-arm
            ghc: '8.8.4'
          - os: ubuntu-24.04-arm
            ghc: '8.10.7'
          - os: ubuntu-24.04-arm
            ghc: '9.0.2'
          # macos-14/ubuntu-24.04-arm (Arm64) doesn't support x87-long-double
          - os: macos-14
            flags: '--flags x87-long-double'
          - os: ubuntu-24.04-arm
            flags: '--flags x87-long-double'
    steps:
      - uses: actions/checkout@v6

      - uses: haskell-actions/setup@v2
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - name: Configure (with UBSan)
        run: |
          # The long-double package misspecifies the alignment for LongDouble.
          # x86-64 psABI specifies that the alignment of long double is 16,
          # but long-double-0.1.1.1 returns 8.
          # For now, I exclude the alignment sanitization.
          cabal configure rounded-hw --ghc-options="-fno-ignore-asserts -optc-fsanitize=undefined -optc-fno-sanitize=alignment -optl-fsanitize=undefined" --enable-tests --enable-benchmarks ${{ matrix.flags }}
          echo "UBSAN_OPTIONS=halt_on_error=1" >> "$GITHUB_ENV"
        if: ${{ runner.os != 'Windows' }}

      - name: Configure (without UBSan)
        run: cabal configure rounded-hw --ghc-options=-fno-ignore-asserts --enable-tests --enable-benchmarks ${{ matrix.flags }}
        if: ${{ runner.os == 'Windows' }}

      - name: Build
        run: cabal build rounded-hw

      - name: Test (rounded-hw-test)
        run: cabal test rounded-hw:rounded-hw-test

      - name: Test (rounded-hw-doctests)
        run: cabal test rounded-hw:rounded-hw-doctests
        if: matrix.os != 'macos-15-intel'
